version: '3.3'

services:
  yamdb_db:
    image: postgres:13.0-alpine
    environment:
        POSTGRES_PASSWORD: changeme
    volumes:
      - /var/lib/postgresql/data/
    networks:
      - yamdb_net
    env_file:
      - ./.env

  yamdb_web:
    image: web2cap/yamdb_final_web:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    networks:
      - yamdb_net
    depends_on:
      - yamdb_db
    env_file:
      - ./.env

  yamdb_nginx:
    image: nginx:1.21.3-alpine
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.yamdb_nginx.entrypoints=websecure"
      - "traefik.http.routers.yamdb_nginx.rule=Host(`yambd.w2c.net.eu.org`)"
      - "traefik.http.routers.yamdb_nginx.tls.certresolver=myresolver"
    ports:
      - "1082:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    networks:
      - yamdb_net
      - traefik_net
    depends_on:
      - yamdb_web

volumes:
  static_value:
  media_value:

networks:
  yamdb_net:
    name: yamdb_net
  traefik_net:
    external: true

