version: '3.3'
services:

  food_frontend:
    image: web2cap/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  food_db:
    image: postgres:13.0-alpine
    environment:
        POSTGRES_PASSWORD: changeme
    volumes:
      - /var/lib/postgresql/data/
    networks:
      - food_net
    env_file:
      - ./.env

  food_web:
    image: web2cap/foodgram_web:latest
    restart: always
    volumes:
      - food_static_value:/app/static/
      - food_media_value:/app/media/
    networks:
      - food_net
    depends_on:
      - food_db
    env_file:
      - ./.env

  food_nginx:
    image: nginx:1.19.3
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.food_nginx.entrypoints=websecure"
      - "traefik.http.routers.food_nginx.rule=Host(`food.w2c.net.eu.org`)"
      - "traefik.http.routers.food_nginx.tls.certresolver=myresolver"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - food_static_value:/var/html/static/
      - food_media_value:/var/html/media/
    networks:
      - food_net
      - traefik_net
    depends_on:
      - food_web

volumes:
  food_static_value:
  food_media_value:

networks:
  food_net:
    name: food_net
  traefik_net:
    external: true
